[build]
builder = "NIXPACKS"
buildCommand = "go build -o main ."

[deploy]
startCommand = "./main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "jwt-auth-backend"
